app/user/forms.py
from flask.ext.wtf import Form
from wtforms import StringField, PasswordField, BooleanField, SubmitField, TextAreaField
from wtforms.validators import DataRequired, Length, Email


class PersonalForm(Form):
	username = StringField('Username', validators=[DataRequired()])
	gravatar_hash = StringField('GravatarHash', validators=[DataRequired()])
	password = PasswordField('Password', validators=[DataRequired()])
	submit = SubmitField('Log In')


class ArticleForm(Form):
	title = StringField('Title', validators=[DataRequired(), Length(1, 64)])
	content = TextAreaField('Content', validators=[DataRequired()])
	tag = StringField('Tag', validators=[DataRequired()])
	summary = TextAreaField('Summary', validators=[DataRequired()])
	submit = SubmitField('Submit')

app/user/__init__.py
from flask import Blueprint

user = Blueprint('user', __name__)

from . import views

app/user/views.py
from flask import render_template, request, redirect, url_for, current_app, flash
from ..models import Article, Tag, User, PlogInfo
from .. import db
from . import user
from flask.ext.login import login_user, current_user, logout_user, login_required
from .forms import PersonalForm, ArticleForm

@user.route('/')
@login_required
def user_index():
	plog_info = PlogInfo.query.first()
	return render_template('user/user-index.html', plog_info = plog_info, current_user = current_user, 
		endpoint = '.user_index')


@user.route('/user-modify', methods = ['GET', 'POST'])
@login_required
def user_modify():
	plog_info = PlogInfo.query.first()
	form = PersonalForm()
	if form.validate_on_submit():
		user = User.query.filter_by(email = current_user.email).first()
		user.modify(username = form.username.data, gravatar_hash = form.gravatar_hash.data, 
			password = form.password.data)
		logout_user()
		return redirect(request.args.get('next') or url_for('main.index'))
	return render_template('user/user-modify.html', plog_info = plog_info, current_user = current_user, 
		 form = form, endpoint = '.user_modify')


@user.route('/tag')
@login_required
def tag_manage():
	plog_info = PlogInfo.query.first()
	tags = Tag.query.all()
	return render_template('user/tag-manage.html', plog_info = plog_info, current_user = current_user, 
		tags = tags, endpoint = '.tag_manage')


@user.route('/article')
@login_required
def article_manage():
	plog_info = PlogInfo.query.first()
	articles = Article.query.all()
	return render_template('user/article-manage.html', plog_info = plog_info, current_user = current_user, 
		articles = articles, endpoint = '.article_manage')



@user.route('/write', methods = ['GET', 'POST'])
@login_required
def write_article():
	plog_info = PlogInfo.query.first()
	form = ArticleForm()
	if form.validate_on_submit():
		tag = Tag.query.filter_by(tag_name = form.tag.data).first()
		if tag is None:
			tag = Tag(tag_name = form.tag.data)
			db.session.add(tag)
			db.session.commit()
		#!!!it may be duplicate
		a = Article(user_id = current_user.id, tag_id = tag.id, title = form.title.data, 
			content = form.content.data, summary = form.summary.data)
		db.session.add(a)
		db.session.commit()

		return redirect(url_for('user.user_index'))
	#print(form.title.data, '---------', form.content.data, '-------', form.tag.data, '---------', form.summary.data)
	return render_template('user/user-write.html', plog_info = plog_info, current_user = current_user, 
		form = form, endpoint = '.write_article')
	

@user.route('/delete-article/<int:id>')
@login_required
def delete_article(id):
	article = Article.query.filter_by(id = id).first()
	db.session.delete(article)
	db.session.commit()
	return redirect(url_for('user.article_manage'))


@user.route('/edit-about')
@login_required
def edit_about():
	pass

app/templates/user/article-manage.html
{% extends 'user/base-user.html' %}

{% block content %}
	<section class="content-right">
		<article>
			<div class="post">
				<h1 class="title">
					Welcome back, {{ current_user.username }}
				</h1>

				{% for article in articles %}
					<p>
						<b>Article{{ article.id }}: </b>{{ article.title }}
						<a class="read_more" href="{{ url_for('user.delete_article', id = article.id) }}">DEL<i class="read_more_arrow"></i> </a>
					</p>
				{% endfor %}

				<a class="read_more" href="#">PENDING<i class="read_more_arrow"></i> </a>
			</div>
		</article>

	</section><!-- Content End -->
{% endblock %}

app/templates/user/base-user.html
<!DOCTYPE html>
<html lang="en">

<head>
	{% block title %}
		<title>{{ plog_info.title }}</title>
	{% endblock %}
	<meta charset="utf-8">
	<meta name="Proverbs" content="www.proverbs.top">
	<link href="{{ url_for('static', filename='css/reset.css') }}" rel="stylesheet">
    <link href="{{ url_for('static', filename='css/main.css') }}" rel="stylesheet">
    <link href="{{ url_for('static', filename='css/login-style.css') }}" rel="stylesheet">
    <link href="{{ url_for('static', filename='css/menubar.css') }}" rel="stylesheet">
    {% block script %}
    {% endblock %}
</head>

<body>
	<header>
		<div class="wrapper">
			<a href="{{ url_for('main.index') }}"><img src="{{ url_for('static', filename='img/logo.png') }}" class="h_logo" alt="Plog" title=""></a>
			<nav>
				<ul class="main_nav">
					<li><a href="{{ url_for('main.logout') }}">Logout</a></li>
				</ul>
			</nav>
		</div>
	</header><!-- Header End -->


	<section class="main2 wrapper">
		<!-- sidebar -->
		<div class="area"></div><nav class="main-menu">
		    <ul>
		        <li>
		            <a href="{{ url_for('user.user_index') }}">
		                <i class="fa fa-home fa-2x"></i>
		                <span class="nav-text">
		                    Account
		                </span>
		            </a>
		          
		        </li>
		        <li class="has-subnav">
		            <a href="{{ url_for('user.user_modify') }}">
		                <i class="fa fa-laptop fa-2x"></i>
		                <span class="nav-text">
		                    Modify Account
		                </span>
		            </a>
		            
		        </li>
		        <li class="has-subnav">
		            <a href="{{ url_for('user.article_manage') }}">
		               <i class="fa fa-list fa-2x"></i>
		                <span class="nav-text">
		                    Article Manage
		                </span>
		            </a>
		            
		        </li>
		        <li class="has-subnav">
		            <a href="{{ url_for('user.tag_manage') }}">
		               <i class="fa fa-folder-open fa-2x"></i>
		                <span class="nav-text">
		                    Tag Manage
		                </span>
		            </a>
		           
		        </li>
		        <li>
		            <a href="#">
		                <i class="fa fa-bar-chart-o fa-2x"></i>
		                <span class="nav-text">
		                    -----Graphs and Statistics
		                </span>
		            </a>
		        </li>
		        <li>
		            <a href="{{ url_for('user.write_article') }}">
		                <i class="fa fa-font fa-2x"></i>
		                <span class="nav-text">
		                    Write Article
		                </span>
		            </a>
		        </li>
		        <li>
		           <a href="#">
		               <i class="fa fa-table fa-2x"></i>
		                <span class="nav-text">
		                    -----Tables
		                </span>
		            </a>
		        </li>
		        <li>
		           <a href="#">
		                <i class="fa fa-map-marker fa-2x"></i>
		                <span class="nav-text">
		                    -----Maps
		                </span>
		            </a>
		        </li>
		        <li>
		            <a href="{{ url_for('user.edit_about') }}">
		               <i class="fa fa-info fa-2x"></i>
		                <span class="nav-text">
		                    Edit About
		                </span>
		            </a>
		        </li>
		    </ul>

		    <ul class="logout">
		        <li>
		           <a href="{{ url_for('main.logout') }}">
		                 <i class="fa fa-power-off fa-2x"></i>
		                <span class="nav-text">
		                    Logout
		                </span>
		            </a>
		        </li>  
		    </ul>
		</nav>


		{% block content %}
		{% endblock %}
	</section>


	
	<footer>
		<div class="wrapper">
			<!-- dashboard -->
			<img class="logo_footer" src="{{ url_for('static', filename='img/logo_footer.png') }}" alt="Blogin" title="">
			<p class="rights">Plog by Proverbs<a href="http://www.proverbs.top" target="_blink">Proverbs.top</a> </p>
			<ul class="social_profiles">
				<li class="f"><a href="http://facebook.com/proverbs" target="_blink"></a></li>
				<li class="t"><a href="http://twitter.com/proverbs" target="_blink"></a></li>
				<li class="be"><a href="http://behance.net/proverbs" target="_blink"></a></li>
				<li class="d"><a href="http://dribbble.com/proverbs" target="_blink"></a></li>
			</ul>
		</div>
	</footer><!-- Footer End -->

</body>

app/templates/user/tag-manage.html
{% extends 'user/base-user.html' %}

{% block content %}
	<section class="content-right">
		<article>
			<div class="post">
				<h1 class="title">
					Welcome back, {{ current_user.username }}
				</h1>

				{% for tag in tags %}
					<p><b>Tag{{ tag.id }}: </b>{{ tag.tag_name }}</p>
				{% endfor %}

				<a class="read_more" href="#">PENDING<i class="read_more_arrow"></i> </a>
			</div>
		</article>

	</section><!-- Content End -->
{% endblock %}

app/templates/user/user-index.html
{% extends 'user/base-user.html' %}

{% block content %}
	<section class="content-right">
		<article>
			<div class="post">
				<h1 class="title">
					Welcome back, {{ current_user.username }}
				</h1>
				
				<p><b>Username: </b>{{ current_user.username }}</p>

				<p><b>Email: </b>{{ current_user.email }}</p>

				<div class="article_image">
					<p><b>Gravatar Profile: </b>{{ current_user.gravatar_hash }}
						<a href="#">
							<img src="https://s.gravatar.com/avatar/{{ current_user.avatar_hash }}" alt="gravatar" title="my_profile">
						</a>
					</p>
				</div>

				<p><b>Password: </b>it is a secret</p>

				<a class="read_more" href="{{ url_for('user.user_modify') }}">Modify Account<i class="read_more_arrow"></i> </a>
			</div>
		</article>

	</section><!-- Content End -->
{% endblock %}

app/templates/user/user-modify.html
{% extends 'user/base-user.html' %}

{% block content %}
	<div class="side-right">
		<section class="widget">
			<h3 class="widget-title">User Email:</h3>
			<div class="textwidget">
				<p>{{ current_user.email }}</p>
			</div>
		
			<h3 class="widget-title">User Info.</h3>
			<form class="search_widget" action="" method="post">
				<!-- it is important, about CSRF -->
				{{ form.hidden_tag() }}
				<p>Username:</p> <p><input type="text" name="username" class="search-field" placeholder="Your username."/></p>
				<br>
				<p>Gravatar:</p> <p><input type="text" name="gravatar_hash" class="search-field" placeholder="Your garvatar hash."/></p>
				<br>
				<p>Password:</p> <p><input type="password" name="password" class="search-field" placeholder="Your password."/></p>
				<br>
				<div>
					<input class="login-form log-btn" type="submit" value="Modify">
				</div>
			</form>
		</section>
	</div><!-- div(sidebar) End -->
{% endblock %}

app/templates/user/user-write.html
{% extends 'user/base-user.html' %}

{% block script %}
	<script src="//cdn.tinymce.com/4/tinymce.min.js"></script>
	<script>tinymce.init({ selector:'textarea'});</script>
{% endblock %}

{% block content %}
	<div class="side-right">
		<section class="widget">
			<form class="search_widget" action="" method="post">
				<!-- it is important, about CSRF -->
				{{ form.hidden_tag() }}
				<h3 class="widget-title">Title:</h3>
				<p><input type="text" name="title" class="title-field" placeholder="Your article title."/></p>
				<br>
				<h3 class="widget-title">Author:</h3>
				<p>{{ current_user.username }}</p>
				<br>
				<textarea name="content">Write your new article.</textarea>
				<br>
				<h3 class="widget-title">Tag:</h3>
				<p><input type="text" name="tag" class="title-field" placeholder="Your tag."/></p>
				<br>
				<h3 class="widget-title">Summary:</h3>
				<p><textarea name="summary" class="title-field">Write your summary of this article.</textarea></p>
				<br>
				<input class="login-form log-btn" type="submit" value="Submit">
			</form>
		</section>
	</div>
{% endblock %}